return{
    {require("colorscheme")},
    --{require("nerdtree")},
    {require("fern")},
    {require("indent-blankline")},
    {require("mini-indentscope")},
    {require("telescope")},
    {require("copilot")},
    {require("copilot-chat")},
    {require("lsp")},
}
