return{
    {require("colorscheme")},
    --{require("nerdtree")},
    {require("fern")},
    {require("indent-blankline")},
    {require("telescope")},
    {require("copilot")},
    {require("copilot-chat")},
}
